From debian:latest
MAINTAINER Bob Clapp <bob@sep.stanford.edu>
RUN apt-get update install git make cmake gcc &&\
  apt-get -y clean
RUN git clone http://zapad.Stanford.EDU/bob/hypercube.git   /opt/hypercube/src && \
    mkdir /opt/hypercube/build && \
    cd /opt/hypercube/build &&\
    cmake ../src &&\
    make install &&\
    rm -rf /opt/hypercube/build
